import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowUpRight, Check, ChevronDown, ChevronRight, Menu, Network, ShieldCheck, X } from 'lucide-react';
import eigiLogo from './assets/eigi-logo.jpeg';
import './styles.css';

const navigation = ['How it works', 'Capabilities', 'For teams', 'School'];
const capabilities = [
  ['01', 'Understand the problem', 'An FDE starts inside the real operating context—not a disconnected ticket queue.'],
  ['02', 'Design the right system', 'Product judgment and technical depth turn ambiguous needs into a plan your team can trust.'],
  ['03', 'Deliver alongside you', 'A senior engineer embeds with your team, builds the system, and leaves it stronger than they found it.'],
];
function BrandLogo() { return <span className="eigi-logo-3d"><img src={eigiLogo} alt="EIGI" /></span>; }
function Arrow() { return <ArrowUpRight className="h-4 w-4" aria-hidden="true" />; }
function StartButton({ className = '', children = 'Book a call' }) { return <button className={`bg-linear-to-b from-[#2B2B2B] to-[#101010] text-sm font-medium text-white transition-opacity hover:opacity-90 ${className}`}>{children}</button>; }
function Reveal({ children, delay = 0, className = '' }) { const ref = useRef(null); const [shown, setShown] = useState(false); useEffect(() => { const node = ref.current; const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setShown(true); observer.unobserve(entry.target); } }, { threshold: 0.15 }); if (node) observer.observe(node); return () => observer.disconnect(); }, []); return <div ref={ref} style={{ transitionDelay: `${delay}ms` }} className={`reveal ${shown ? 'reveal--shown' : ''} ${className}`}>{children}</div>; }
function GlowCard({ children, className = '' }) { const move = (event) => { const box = event.currentTarget.getBoundingClientRect(); event.currentTarget.style.setProperty('--x', `${event.clientX - box.left}px`); event.currentTarget.style.setProperty('--y', `${event.clientY - box.top}px`); }; return <article onMouseMove={move} className={`glow-card ${className}`}>{children}</article>; }
function useTypewriter(text, speed = 42) { const [displayed, setDisplayed] = useState(''); useEffect(() => { let index = 0; const timer = window.setInterval(() => { index += 1; setDisplayed(text.slice(0, index)); if (index >= text.length) window.clearInterval(timer); }, speed); return () => window.clearInterval(timer); }, [text, speed]); return { displayed, done: displayed.length === text.length }; }
function InquirySection() { const { displayed, done } = useTypewriter("Let's make the\nnext move clear."); const [services, setServices] = useState([]); const options = ['AI systems', 'Product delivery', 'Workflow automation', 'Team enablement']; const toggleService = (service) => setServices((current) => current.includes(service) ? current.filter((item) => item !== service) : [...current, service]); return <section className="inquiry-section inquiry-section--motion" id="inquiry"><video className="inquiry-video" autoPlay loop muted playsInline preload="metadata"><source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260601_110537_3a579fa0-7bbc-4d94-9d25-0e816c7840f5.mp4" type="video/mp4" /></video><div className="inquiry-shell"><Reveal><p className="eyebrow">Start a conversation</p><h2>{displayed}{!done && <span className="type-cursor" />}</h2><p className="inquiry-copy">Tell us what is stuck, changing, or simply taking too much effort. We will help you find the right starting point.</p></Reveal><Reveal delay={120} className="service-picker"><div><h3>What should move forward?</h3><p>Select every area that applies.</p></div><div className="service-pills">{options.map((service) => <button type="button" key={service} onClick={() => toggleService(service)} className={services.includes(service) ? 'service-pill service-pill--active' : 'service-pill'}>{services.includes(service) && <Check className="h-3.5 w-3.5" />}{service}</button>)}</div><div className={services.length ? 'inquiry-status inquiry-status--active' : 'inquiry-status'}>{services.length ? <><span>Ready to discuss: {services.join(', ')}</span><button type="button">Continue <Arrow /></button></> : <span>Select the areas you want to discuss.</span>}</div></Reveal></div></section>; }

function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { document.body.style.overflow = menuOpen ? 'hidden' : ''; return () => { document.body.style.overflow = ''; }; }, [menuOpen]);
  const linkFor = (item) => item === 'Capabilities' ? '#capabilities' : '#approach';
  return <div className="scroll-shell" id="top">
    <section className="nexum-hero relative h-screen min-h-[680px] w-full overflow-hidden"><video className="nexum-video absolute inset-0 h-full w-full object-cover" autoPlay loop muted playsInline><source src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260809_012548_ef22562c-c0ae-4816-ad9d-f8922af4e6a7.mp4" type="video/mp4" /></video><div className="ops-field" aria-hidden="true"><span /><span /><span /></div><div className="nexum-content relative z-10 flex h-full flex-col">
      <nav className="flex items-center justify-between px-5 py-5 sm:px-8 sm:py-6 lg:px-12"><a href="#top" className="flex items-center gap-2.5 text-sm font-semibold tracking-wide text-[#010101] lg:text-white" aria-label="EIGI home"><BrandLogo /><span>EIGI AI</span></a><div className="hidden items-stretch gap-3 md:flex"><div className="flex gap-1 rounded-full bg-white/10 px-1.5 py-1.5 backdrop-blur-lg">{navigation.map((item) => <a key={item} href={linkFor(item)} className="rounded-full px-4 py-1.5 text-sm font-medium text-white/80 transition-colors hover:bg-white/10 hover:text-white">{item === 'Capabilities' ? <span className="flex items-center gap-1">{item}<ChevronDown className="h-3.5 w-3.5" /></span> : item}</a>)}</div><StartButton className="self-stretch rounded-full px-5" children="Talk to EIGI" /></div><button onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Close menu' : 'Open menu'} className="relative z-50 grid h-10 w-10 place-items-center rounded-full bg-white/10 backdrop-blur-lg md:hidden"><Menu className={`absolute h-5 w-5 text-[#010101] transition-all duration-300 ${menuOpen ? 'rotate-90 scale-0 opacity-0' : 'opacity-100'} lg:text-white`} /><X className={`absolute h-5 w-5 text-[#010101] transition-all duration-300 ${menuOpen ? 'opacity-100' : '-rotate-90 scale-0 opacity-0'} lg:text-white`} /></button></nav>
      <div onClick={() => setMenuOpen(false)} className={`fixed inset-0 z-40 bg-black/80 backdrop-blur-md transition-opacity duration-300 md:hidden ${menuOpen ? 'opacity-100' : 'pointer-events-none opacity-0'}`} /><aside className={`fixed right-0 top-0 z-40 flex h-full w-72 flex-col bg-black/90 backdrop-blur-xl transition-transform duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] md:hidden ${menuOpen ? 'translate-x-0' : 'translate-x-full'}`}><div className="flex flex-col gap-2 px-6 pt-24">{navigation.map((item, index) => <a href={linkFor(item)} onClick={() => setMenuOpen(false)} key={item} style={{ transitionDelay: menuOpen ? `${(index + 1) * 60}ms` : '0ms' }} className={`flex items-center justify-between rounded-xl px-4 py-3.5 text-base font-medium text-white/80 transition-all duration-300 hover:bg-white/10 hover:text-white ${menuOpen ? 'translate-x-0 opacity-100' : 'translate-x-6 opacity-0'}`}>{item}{item === 'Capabilities' && <ChevronDown className="h-4 w-4" />}</a>)}</div><div className={`mt-auto px-6 pb-10 transition-all delay-300 duration-[400ms] ${menuOpen ? 'translate-y-0 opacity-100' : 'translate-y-4 opacity-0'}`}><StartButton className="w-full rounded-full px-6 py-3" children="Talk to EIGI" /></div></aside>
      <main className="mt-auto flex flex-col gap-6 px-5 pb-8 sm:gap-8 sm:px-8 sm:pb-12 lg:flex-row lg:items-end lg:justify-between lg:px-12 lg:pb-16"><div className="max-w-xl"><p className="mb-4 font-mono text-[10px] uppercase tracking-[.18em] text-[#010101]/65 lg:text-white/80">Forward deployed engineering</p><div className="hero-proof"><span><i /><i /><i /></span> Built for high-context client work</div><h1 className="text-3xl font-semibold leading-[1.1] tracking-tight text-[#010101] sm:text-4xl lg:text-[3.5rem] lg:text-white">We go to your client. We make AI work.</h1><div className="mt-6 flex flex-col gap-3 sm:mt-8 sm:inline-flex sm:flex-row sm:items-center sm:rounded-full sm:bg-white sm:p-1.5"><input type="email" placeholder="Type your email" aria-label="Email address" className="rounded-full bg-white px-5 py-3 text-sm text-gray-900 outline-none placeholder:text-gray-400 sm:w-64 sm:rounded-none sm:bg-transparent sm:px-4 sm:py-2" /><StartButton className="rounded-full px-6 py-3 sm:py-2.5" children="Start a conversation" /></div><div className="signal-strip" aria-label="Forward deployed engineering principles"><div><b>01</b><span>Client context</span></div><div><b>02</b><span>Senior delivery</span></div><div><b>03</b><span>Team handoff</span></div></div></div><div className="flex w-full flex-col gap-4 sm:flex-row lg:w-auto lg:gap-5"><GlowCard className="flex flex-col justify-between rounded-2xl bg-white/10 p-5 backdrop-blur-lg sm:w-64 sm:p-6"><span className="font-mono text-3xl font-normal tracking-tight text-[#010101] sm:text-4xl lg:text-white">FDE</span><p className="mt-3 text-sm leading-relaxed text-[#010101]/70 sm:mt-4 lg:text-white/70">A senior engineer embedded where outcomes matter most.</p></GlowCard><GlowCard className="rounded-2xl bg-white/10 p-5 backdrop-blur-lg sm:w-64 sm:p-6"><div className="mb-3 flex items-center gap-2 sm:mb-4"><span className="grid h-6 w-6 place-items-center rounded bg-black text-xs font-bold text-white">E</span><span className="text-sm font-semibold text-[#010101] lg:text-white">EIGI School</span></div><p className="text-sm leading-relaxed text-[#010101]/80 lg:text-white/80">We develop engineers who understand clients, systems, and the work in between.</p><a href="#approach" className="mt-5 flex items-center gap-1 text-sm font-semibold text-[#010101] lg:text-white">See our approach <Arrow /></a></GlowCard></div></main>
    </div></section>
    <section id="approach" className="paper-section"><Reveal className="editorial-grid"><div><p className="eyebrow">A dual mission</p><h2>We work inside<br />the <em>real problem.</em></h2><div className="button-row"><StartButton className="rounded-full px-5 py-3" children="Find an FDE" /><a className="outline-cta" href="#capabilities">Explore capabilities <Arrow /></a></div></div><div className="editorial-copy"><p>We hand-pick and embed seasoned engineers directly inside your client team. They bring context, technical range, and the habit of solving hard problems shoulder-to-shoulder.</p><dl><div><dt>01</dt><dd>Client context before code</dd></div><div><dt>02</dt><dd>Senior ownership from day one</dd></div><div><dt>03</dt><dd>Software that survives handoff</dd></div></dl></div></Reveal></section>
    <section className="client-journey"><div className="journey-sticky"><Reveal><p className="eyebrow">The FDE operating system</p><h2>Forward deployed.<br /><em>Deeply embedded.</em></h2><p className="journey-intro">A continuous path from unknowns to useful software—made visible for both clients and engineers.</p></Reveal><div className="journey-orbit"><span className="orbit-core">EIGI</span><i className="orbit-dot orbit-dot--one" /><i className="orbit-dot orbit-dot--two" /><i className="orbit-dot orbit-dot--three" /></div><div className="system-pulse"><span className="pulse-dot" /> Embedded systems online <Activity className="h-3.5 w-3.5" /></div></div><div className="journey-steps"><Reveal delay={60}><article><span>01 / DISCOVER</span><h3>Map the real work</h3><p>We join the conversation, trace the bottlenecks, and identify the decision that unlocks progress.</p></article></Reveal><Reveal delay={120}><article><span>02 / BUILD</span><h3>Ship the useful thing</h3><p>An FDE designs and delivers with your people—not across a long chain of outsourced handoffs.</p></article></Reveal><Reveal delay={180}><article><span>03 / ENABLE</span><h3>Leave the team stronger</h3><p>Systems, documentation, and shared capability remain after the immediate project is done.</p></article></Reveal></div></section>
    <section id="capabilities" className="capabilities-section"><Reveal className="capability-intro"><p className="eyebrow">How we help</p><h2>Build what<br /><em>matters next.</em></h2><p>One FDE can clarify a product, connect an operation, or make a stuck workflow finally move.</p></Reveal><div className="capability-panel">{capabilities.map(([index, title, text], i) => <Reveal key={index} delay={i * 100}><article className="capability-row"><span>{index}</span><div><h3>{title}</h3><p>{text}</p></div><ChevronRight className="capability-chevron h-5 w-5" /></article></Reveal>)}</div></section>
    <section className="system-proof"><Reveal className="proof-heading"><p className="eyebrow">A clear operating picture</p><h2>See the work<br /><em>move forward.</em></h2><p>Illustrative interface—not a client dashboard. It shows the level of clarity an embedded team can create.</p></Reveal><Reveal delay={100} className="ops-console"><div className="console-top"><div><span className="console-kicker">ENGAGEMENT / 04</span><strong>Client operating map</strong></div><span className="console-status"><i /> In motion</span></div><div className="console-body"><div className="console-rail"><span className="rail-active"><Check /> Intake mapped</span><span className="rail-active"><Check /> Systems connected</span><span className="rail-current"><Network /> Automation in build</span><span><ShieldCheck /> Team enabled</span></div><div className="console-chart"><div className="chart-header"><span>Decision velocity</span><strong>+38%</strong></div><div className="chart-bars">{[35, 48, 40, 66, 59, 77, 91].map((height, index) => <i key={index} style={{ height: `${height}%` }} />)}</div><div className="chart-labels"><span>Week 1</span><span>Week 7</span></div></div></div><p className="console-foot">Sample visualisation for a forward-deployed engagement.</p></Reveal></section>
    <section className="closing-section"><Reveal><p className="eyebrow">Start with the messy version</p><h2>Bring us the hard<br />part. <em>We’ll build through it.</em></h2><p>Tell us where the work is stuck. We’ll bring the right engineer into the room.</p><div className="button-row"><a className="outline-cta outline-cta--dark" href="#inquiry">Start an inquiry <Arrow /></a><a className="outline-cta outline-cta--dark" href="#top">Back to top <Arrow /></a></div></Reveal><Reveal delay={120} className="engagement-brief"><div className="brief-title"><span>What happens next</span><p>A practical start, not a long sales process.</p></div><div className="brief-steps"><article><b>01</b><div><strong>Share the context</strong><p>A short note on the blocked workflow, team, and outcome.</p></div></article><article><b>02</b><div><strong>Scope the right move</strong><p>We identify whether an embedded engineer can materially help.</p></div></article><article><b>03</b><div><strong>Start in the work</strong><p>One accountable senior engineer, working alongside your team.</p></div></article></div></Reveal><span className="closing-word">EIGI</span></section><InquirySection /><footer className="site-footer"><span>© {new Date().getFullYear()} EIGI AI</span><span>Forward deployed engineering</span></footer>
  </div>;
}
createRoot(document.getElementById('root')).render(<App />);
